name: popular_movies
description: Retrieves and displays the most popular movies
version: 0.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.8.7
  data_connection_checker: ^0.3.4
  equatable: ^0.6.0
  flutter_bloc: ^0.21.0
  get_it: ^3.0.1
  http: ^0.12.0+2
  moor_flutter: ^2.0.0
  shared_preferences: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  mockito: ^4.1.1
  moor_generator: ^2.0.0

flutter:
